name: ABC workflow

on:
  workflow_call:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && exit 1
  b:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
  c:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
