name: Cancel action fail-fast

on: [push, pull_request]

permissions:
  actions: write 

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && exit 1
      - uses: andymckay/cancel-action@0.4
        if: failure()
  b:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
      - uses: andymckay/cancel-action@0.4
        if: failure()
  c:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
      - uses: andymckay/cancel-action@0.4
        if: failure()
  d:
    runs-on: ubuntu-latest
    needs: [a, b, c]
    steps:
      - run: exit 0
