name: Dependency fail-fast

on: [push, pull_request]


jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && exit 1
  b:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
  c:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
  d:
    runs-on: ubuntu-latest
    needs: [a, b, c]
    steps:
      - run: exit 0
