name: Matrix fail-fast

on: [push, pull_request]

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        letter: [a, b, c]
        include:
          - letter: a
            timeout: 5
            code: 1
          - letter: b
            timeout: 30
            code: 0
          - letter: c
            timeout: 60
            code: 0
    steps:
      - run: sleep ${{ matrix.timeout }} && exit ${{ matrix.code }}
  d:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - run: exit 0
